name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install build-essential nasm xorriso grub-pc-bin grub-common mtools
    
    - name: Build Project
      run: make

    - name: Upload Binary
      id: upload-step
      uses: actions/upload-artifact@v4
      with:
        name: crix-iso-artifact
        path: ./crix.iso

    - name: Output Download URL
      run: echo "Download your binary here -> ${{ steps.upload-step.outputs.artifact-url }}"
